name: Run Tests
# Trigger this workflow on every push or pull request
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Flask
        run: python -m pip install Flask
      - name: Run Tests
        run: python -m unittest discover -v